src/ui/Island/RealmDetails/Quests/QuestsDetails.tsx

In case we don't want to confuse users with super high XP... 🤫

Hide real allocatable xp for now

---

src/ui/Island/RealmDetails/LeaderboardList/LeaderboardItem.tsx

Cut the decimal part on the leaderboard

---

src/redux-state/selectors/realm.ts
src/ui/Island/RealmDetails/RealmBanners/BannerRewards.tsx
src/ui/Island/RealmDetails/StakingForms/StakeForm.tsx
src/ui/Island/RealmDetails/StakingForms/UnstakeForm.tsx
src/ui/Island/index.tsx

Resolves https://github.com/tahowallet/dapp/issues/672
- add events for claiming XP
- fix problem with tracking realm names on stake/unstake

Posthog improvements

---

docs/local-env-setup.md
docs/xp-distribution.md

Resolves https://github.com/tahowallet/dapp/issues/648
Update local env setup and XP distribution docs
- simplify the setup instruction
- remove duplicated and outdated parts

Documentation update

---

.github/workflows/test-list/release-test-list.md

Minor updates to the release tests:
Made notes for testing XP and fixed a type-o

Minor updates to release-test-list.md

---

src/shared/constants/realms-data.ts

Add missing property to `realms-data`

---

src/shared/constants/realms.ts
src/shared/hooks/reflect.ts
src/shared/types/reflect.ts
src/ui/Island/Cursor/CursorLabel.tsx

Load reflect realm icons dynamically with a path relative to component

Load reflect icons dynamically

---

src/assets/xp-data.json
src/redux-state/thunks/island.ts
src/shared/constants/realms.ts
src/shared/contracts/realms.ts
src/shared/contracts/realmsData.ts
src/shared/services/storage.ts
src/ui/Island/RealmDetails/LeaderboardList/index.tsx
src/ui/Island/RealmDetails/Quests/QuestsRewards.tsx

⚠️  Merging this PR will add the realm - please approve but not merge before we are ready to publish the realm
Refactor to prepare for new realm
- allow adding realm contracts by address
- update existing realms to add them by address not name
- removed the env flag to make it easier in the code to control the data - we need to update the storage version when the Base realm should become visible, it will be easier to just merge the PR to publish than to guard multiple places with feature flags
Adding new realm
- added Base realm by contract address
- updated Leaderboard placeholder to match expected XP drop date
- updated storage version to allow users to reload the realms data they have cached in local storage

Connect Base realm

---

src/assets/questline-data.json
src/ui/Assistant/AssistantContent/AssistantFirstRealm.tsx
src/ui/Assistant/AssistantContent/AssistantWelcome.tsx

- galxe questline text fixed
- number of realms fixed

Minor fixes

---

.github/workflows/update-environments.yml

As Andrea is leaving the project, I'm changing the reviewer of the deployment PRs to myself.

Update reviewer of deployment PRs

---

src/shared/components/Accordion.tsx
src/shared/components/RealmPanel/RealmDetailsPanel/index.tsx
src/shared/components/RealmPanel/RealmPanelAccordion/GuardiansSection.tsx
src/shared/components/RealmPanel/RealmPanelAccordion/StakeUnstakeSection.tsx
src/shared/components/RealmPanel/RealmPanelAccordion/index.tsx

Resolves #740 
- Added new `Accordion` type
- Added `isDisabled` prop to `Accordion`

Accordion panels

---

package.json
src/shared/hooks/reflect.ts
src/shared/hooks/wallets.ts
src/shared/types/reflect.ts
src/shared/utils/reflect.ts
src/ui/DApps/DesktopDApp.tsx
src/ui/Island/IslandPresence.tsx
yarn.lock

PR fixing reflect issues
`component=RoomDO doID=2c6330d03afb624a4ff346e2b01457962428cab1cb8309ea070a7e3ca08525d5 roomID=/ wsid=H6hCaalCugPRmK_fFp0LY clientID=35af2e3b-99f9-4ba5-8176-522d9b231114 clientGroupID=d36a9504-f10f-4ca7-80de-f1418677e953 userID=_tje_WNFe00VnTez25Yh6 network.client.ip=79.143.107.106 http.useragent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 lockFn=handleConnection lockHoldID=21ov719ob9w WebSocket ErrorEvent for client 35af2e3b-99f9-4ba5-8176-522d9b231114 {"filename":"","message":"Uncaught Error: Network connection lost.","lineno":0,"colno":0} {"name":"Error","message":"Network connection lost.","stack":"Error: Network connection lost."}`
`[skipping unknown mutator, {args=true, …

Fix reflect

---

src/shared/constants/external-links.ts
src/ui/Onboarding/JoinWaitlist.tsx
src/ui/Onboarding/index.tsx

Resolves https://github.com/tahowallet/dapp/issues/791

Chnage waitlist link and CTA

---

src/redux-state/selectors/wallet.ts
src/redux-state/slices/wallet.ts
src/redux-state/thunks/wallet.ts
src/shared/components/Avatar.tsx
src/shared/components/KonvaVideo.tsx
src/shared/components/RealmCutout/RealmCutout.tsx
src/shared/components/RealmCutout/RealmPin.tsx
src/shared/utils/misc.ts
src/shared/utils/names.ts
src/ui/Island/IslandRealmsDetails/RealmPin.tsx
src/ui/Nav/AccountInfo.tsx

- We were accidentally displaying avatar urls as names 🙈
- Added `KonvaVideo` component to handle video on canvas
- Added compatibilty with video as user avatar

Display video as user avatar

---

src/shared/hooks/island.ts
src/ui/Island/Realm.tsx

Fix: All realm icons are shown after closing realm panel

---

package.json
src/assets/questline-data.json
src/ui/Island/RealmDetails/Quests/QuestItem.tsx
yarn.lock

- Updated the Base Realm quest
- Updated `Markdown` render in `QuestItem`

Update Base Realm quest

---

src/assets/questline-data.json

Fix typo in Base quest

---

src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsHeader.tsx
src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsQuestInfo.tsx
src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsQuests.tsx
src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsSection.tsx

Resolves #784 
- Fixed wrap on too long names
- Fixed border separating sections in realm panel

New realm UI issues

---

src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsChallengeItem.tsx
src/shared/components/RealmPanel/RealmDetailsPanel/RealmDetailsChallenges.tsx

Updating local storage after clicking new challenge was not implemented in new UI

Add missing functionality to challenge item

---

src/shared/constants/realms.ts
src/shared/services/storage.ts

Hiding zkSync for new realm UI release, will bring it after release is completed

Hide zkSync realm before new realm UI release

---

src/ui/Island/RealmPanel/RealmPanelCountdown.tsx

To get better UX for now let's change season duration to 7 weeks so it indicates this is the last week of beta.

Hardcode season duration

---

src/shared/constants/external-links.ts

Resolves #875
Resolves #876 
Added new link to Galxe campaign

Update Galxe campaign link

---

src/shared/hooks/wallets.ts

Fixes error with `ens` destructuring

Fix ens destructuring

---

src/shared/hooks/assistant.ts
src/shared/hooks/realm.ts
src/ui/Assistant/index.tsx

Hidden some of assistant messages

Hide assistant messages

---

.github/workflows/test-list/release-test-list.md

We've changed some functionalities due to first stage of Beta End. Our release testlist needs to reflect the new expected behavior.

Update release test list after Beta End Stage 1

---

src/ui/DApps/IslandView.tsx
src/ui/Island/RealmPanel/RealmDetailsPanel/RealmDetailsRewards.tsx
src/ui/Island/RealmPanel/RealmPanelCountdown.tsx

Update XP claim date to Jan 15 2024

Update XP claim date
